// <auto-generated />
using System;
using BusSeatManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusSeatManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506162805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("BusSeatManagement.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentSeatId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OriginalFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId");

                    b.HasIndex("BusId");

                    b.HasIndex("CurrentSeatId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BusSeatManagement.Models.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("BusSeatManagement.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SeatId");

                    b.HasIndex("BusId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("BusSeatManagement.Models.SeatTransaction", b =>
                {
                    b.Property<int>("SeatTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DifferenceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NewFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NewSeatId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OldFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OldSeatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeatTransactionId");

                    b.HasIndex("BookingId");

                    b.ToTable("SeatTransactions");
                });

            modelBuilder.Entity("BusSeatManagement.Models.Booking", b =>
                {
                    b.HasOne("BusSeatManagement.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusSeatManagement.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("CurrentSeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("BusSeatManagement.Models.Seat", b =>
                {
                    b.HasOne("BusSeatManagement.Models.Bus", "Bus")
                        .WithMany("Seats")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusSeatManagement.Models.SeatTransaction", b =>
                {
                    b.HasOne("BusSeatManagement.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BusSeatManagement.Models.Bus", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
